package ipc1.practica2_201701010;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class Productos extends javax.swing.JFrame {
    
    public static int fila;
    public static int contadorProductos;
    public static int kilometros;
    public static int montoTotal;
    
    public static String producto;
    public static String precio;
    public static String vehiculoSeleccionado;
    public static String fechaHoraEntregaFormateada;
    public static String fechaHoraFormateada;
    
    public Productos() {
        initComponents();
        productos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListadoPedidos = new javax.swing.JTable();
        AgregarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        VehiculoBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        KilometrosTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ConfiramrBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Totallbl = new javax.swing.JLabel();
        HistorialBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        agregarPrBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Productos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Pedido");

        ListadoProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ListadoProductos);
        if (ListadoProductos.getColumnModel().getColumnCount() > 0) {
            ListadoProductos.getColumnModel().getColumn(1).setMinWidth(100);
            ListadoProductos.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        ListadoPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ListadoPedidos);
        if (ListadoPedidos.getColumnModel().getColumnCount() > 0) {
            ListadoPedidos.getColumnModel().getColumn(0).setMinWidth(200);
            ListadoPedidos.getColumnModel().getColumn(0).setMaxWidth(200);
            ListadoPedidos.getColumnModel().getColumn(1).setMinWidth(100);
            ListadoPedidos.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        AgregarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgregarBtn.setText("Agregar Producto Seleccionado al Pedido");
        AgregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Vehículo:");

        VehiculoBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VehiculoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motocicleta", "Automóvil", "Bicicleta", " " }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Distancia a recorrer:");

        KilometrosTxt.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Km");

        ConfiramrBtn.setBackground(new java.awt.Color(153, 255, 153));
        ConfiramrBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfiramrBtn.setText("CONFIRMAR");
        ConfiramrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiramrBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total: Q");

        Totallbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Totallbl.setText("0");

        HistorialBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HistorialBtn.setText("Historial");
        HistorialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Envio de Pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        agregarPrBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarPrBtn.setText("Agregar Producto");
        agregarPrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(269, 269, 269))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(VehiculoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(KilometrosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HistorialBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Totallbl)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ConfiramrBtn)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(AgregarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarPrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AgregarBtn)
                        .addGap(9, 9, 9)
                        .addComponent(agregarPrBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Totallbl)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(VehiculoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(KilometrosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(ConfiramrBtn)
                            .addComponent(HistorialBtn)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBtnActionPerformed
        fila = ListadoProductos.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método sin agregar el producto al pedido
        }else{
            producto = ListadoProductos.getModel().getValueAt(fila, 0).toString();
            precio = ListadoProductos.getModel().getValueAt(fila, 1).toString();
        
            Pedido();
        }
        
    }//GEN-LAST:event_AgregarBtnActionPerformed

    
    private void ConfiramrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiramrBtnActionPerformed
        // TODO add your handling code here:
        
        LocalDateTime fechaHora = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy - HH:mm:ss");
        fechaHoraFormateada = fechaHora.format(formato);
        
        montoTotal = Integer.parseInt(Totallbl.getText());
        vehiculoSeleccionado = VehiculoBox.getSelectedItem().toString();
        kilometros = Integer.parseInt(KilometrosTxt.getText());

        // Obtener la fecha y hora actual
        LocalDateTime fechaHoraActual = LocalDateTime.now();

        // Agregar la cantidad de minutos según la selección del ComboBox
        int minutosExtra = 0;
        if (vehiculoSeleccionado.equals("Motocicleta")) {
            minutosExtra = 10;
        } else if (vehiculoSeleccionado.equals("Automóvil")) {
            minutosExtra = 20;
        } else if (vehiculoSeleccionado.equals("Bicicleta")) {
            minutosExtra = 30;
        }

        LocalDateTime fechaHoraEntrega = fechaHoraActual.plusMinutes(minutosExtra + (kilometros*2));

        // Formatear la fecha y hora de entrega
        fechaHoraEntregaFormateada = fechaHoraEntrega.format(formato);

        // Aquí puedes hacer lo que necesites con las variables (ejemplo: imprimir, almacenar en una base de datos, etc.)
        System.out.println("Monto Total: " + montoTotal);
        System.out.println("Vehículo seleccionado: " + vehiculoSeleccionado);
        System.out.println("Kilómetros: " + kilometros);
        System.out.println("Fecha y Hora: " + fechaHoraFormateada);
        System.out.println("Fecha y Hora de Entrega: " + fechaHoraEntregaFormateada);
        
        // Eliminar todos los datos de la tabla
        DefaultTableModel modelo = (DefaultTableModel) ListadoPedidos.getModel();
        modelo.setRowCount(0);
        
    }//GEN-LAST:event_ConfiramrBtnActionPerformed

    private void HistorialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Historial hi = new Historial();
        hi.setVisible(true);
    }//GEN-LAST:event_HistorialBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VerRecorrido vr = new VerRecorrido();
        vr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregarPrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPrBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AgregarProducto ap = new AgregarProducto();
        ap.setVisible(true);
    }//GEN-LAST:event_agregarPrBtnActionPerformed

    
    
    public void productos(){
        DefaultTableModel modeloProductos = (DefaultTableModel) ListadoProductos.getModel();
        modeloProductos.setValueAt("Pizza Grande Especialidad", 0, 0);
        modeloProductos.setValueAt("Pizza Grande 1 Ingrediente", 1, 0);
        modeloProductos.setValueAt("Pizza Mediana 1 Ingrediente", 2, 0);
        modeloProductos.setValueAt("Pizza Pesonal 1 Ingrediente", 3, 0);
        modeloProductos.setValueAt( "Q 120", 0, 1);
        modeloProductos.setValueAt("Q 100", 1, 1);
        modeloProductos.setValueAt( "Q 50", 2, 1);
        modeloProductos.setValueAt("Q 35", 3, 1);
    }
    
    public void Pedido(){
        DefaultTableModel modeloPedido = (DefaultTableModel) ListadoPedidos.getModel();
        modeloPedido.addRow(new Object[]{producto, precio});
        
        // Calcular el total sumando los precios de los productos en la tabla ListadoPedidos
        int total = 0;
        for (int i = 0; i < modeloPedido.getRowCount(); i++) {
            String precioProductoStr = modeloPedido.getValueAt(i, 1).toString();
            int precioProducto = Integer.parseInt(precioProductoStr.substring(2)); // Eliminar el símbolo de moneda "Q" y convertir a entero
            total += precioProducto;
        }
        // Actualizar el label Totallbl con el total calculado
        Totallbl.setText(String.valueOf(total));
    }
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBtn;
    private javax.swing.JButton ConfiramrBtn;
    private javax.swing.JButton HistorialBtn;
    private javax.swing.JTextField KilometrosTxt;
    private javax.swing.JTable ListadoPedidos;
    private javax.swing.JTable ListadoProductos;
    private javax.swing.JLabel Totallbl;
    private javax.swing.JComboBox<String> VehiculoBox;
    private javax.swing.JButton agregarPrBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
