package ipc1.practica2_201701010;

import javax.swing.JLabel;

public class VerRecorrido extends javax.swing.JFrame {

    
    public VerRecorrido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DestinoLbl = new javax.swing.JLabel();
        Vehiculo1Lbl = new javax.swing.JLabel();
        Iniciar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DistanciaLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Iniciar2 = new javax.swing.JButton();
        Iniciar3 = new javax.swing.JButton();
        Vehiculo3Lbl = new javax.swing.JLabel();
        Vehiculo3Lbl1 = new javax.swing.JLabel();
        IniciarTodos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Distancia2Lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Distancia3Lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualizar Pedidos");

        DestinoLbl.setBackground(new java.awt.Color(51, 102, 255));
        DestinoLbl.setOpaque(true);

        Vehiculo1Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moto.png"))); // NOI18N

        Iniciar1.setText("Iniciar");
        Iniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Distancia:");

        DistanciaLbl.setText("5");

        jLabel3.setText("Km");

        Iniciar2.setText("Iniciar");
        Iniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar2ActionPerformed(evt);
            }
        });

        Iniciar3.setText("Iniciar");
        Iniciar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar3ActionPerformed(evt);
            }
        });

        Vehiculo3Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moto.png"))); // NOI18N

        Vehiculo3Lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Moto.png"))); // NOI18N

        IniciarTodos.setText("Iniciar Todos");
        IniciarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarTodosActionPerformed(evt);
            }
        });

        jLabel2.setText("Distancia:");

        jLabel4.setText("Distancia:");

        Distancia2Lbl.setText("10");

        jLabel6.setText("Km");

        Distancia3Lbl.setText("20");

        jLabel8.setText("Km");

        jLabel9.setText("Vehículo 1");

        jLabel10.setText("Vehículo 2");

        jLabel11.setText("Vehículo 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DistanciaLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))
                                .addComponent(Iniciar1)
                                .addComponent(Iniciar3)
                                .addComponent(Iniciar2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Distancia2Lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(4, 4, 4)
                                    .addComponent(Distancia3Lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vehiculo3Lbl)
                            .addComponent(Vehiculo3Lbl1)
                            .addComponent(Vehiculo1Lbl)))
                    .addComponent(IniciarTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(DestinoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DestinoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(DistanciaLbl)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Iniciar1))
                    .addComponent(Vehiculo1Lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Vehiculo3Lbl1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Distancia2Lbl)
                            .addComponent(jLabel6))
                        .addGap(9, 9, 9)
                        .addComponent(Iniciar2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Vehiculo3Lbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Distancia3Lbl)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Iniciar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(IniciarTodos)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar1ActionPerformed
        // TODO add your handling code here:
        Recorrido rec = new Recorrido(Vehiculo1Lbl,5);
        
        rec.start();
    }//GEN-LAST:event_Iniciar1ActionPerformed

    private void Iniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar2ActionPerformed
        // TODO add your handling code here:
        Recorrido rec = new Recorrido(Vehiculo3Lbl1,7);
        
        rec.start();
    }//GEN-LAST:event_Iniciar2ActionPerformed

    private void Iniciar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar3ActionPerformed
        // TODO add your handling code here:
        Recorrido rec = new Recorrido(Vehiculo3Lbl,10);
        
        rec.start();
        
    }//GEN-LAST:event_Iniciar3ActionPerformed

    private void IniciarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarTodosActionPerformed
        // TODO add your handling code here:
        Recorrido rec1 = new Recorrido(Vehiculo1Lbl,5);
        Recorrido rec2 = new Recorrido(Vehiculo3Lbl1,7);
        Recorrido rec3 = new Recorrido(Vehiculo3Lbl,10);
        
        rec1.start();
        rec2.start();
        rec3.start();
        
        
    }//GEN-LAST:event_IniciarTodosActionPerformed

    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VerRecorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VerRecorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VerRecorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VerRecorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerRecorrido().setVisible(true);
            }
        });
    }
    
    
    public JLabel getDestino(){
        return DestinoLbl;
    }
    
    public JLabel getVehiculo(){
        return Vehiculo1Lbl; 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel DestinoLbl;
    private javax.swing.JLabel Distancia2Lbl;
    private javax.swing.JLabel Distancia3Lbl;
    private javax.swing.JLabel DistanciaLbl;
    private javax.swing.JButton Iniciar1;
    private javax.swing.JButton Iniciar2;
    private javax.swing.JButton Iniciar3;
    private javax.swing.JButton IniciarTodos;
    public static javax.swing.JLabel Vehiculo1Lbl;
    public static javax.swing.JLabel Vehiculo3Lbl;
    public static javax.swing.JLabel Vehiculo3Lbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
